### PR TITLE
Add arm64 platform support to Docker builds

### PR DESCRIPTION
**Pull request by suin**
#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [x] Y 

re #63 

#### 2. What is the scope of this PR (e.g. component or file name):

.github/workflows/release.yaml

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [x] Other

This PR adds ARM64 support to the Docker images by modifying the GitHub Actions workflow to build multi-architecture images. This enhancement enables users to run the project natively on ARM64 systems like Apple Silicon Macs and AWS Graviton instances.

Changes:
- Updated `.github/workflows/release.yaml` to build images for both AMD64 and ARM64
- No changes to Dockerfile or Go code required as they already support cross-compilation

Implementation:
```yaml
# Before
platforms: linux/amd64

# After
platforms: linux/amd64,linux/arm64
```

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [x] N

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [x] Manual test (add detailed scripts or steps below)
- [ ] Other

Manual testing performed:
1. Build and Registry Testing:
   - Successfully built both AMD64 and ARM64 images using GitHub Actions in fork repository
   - Successfully pushed multi-arch images to Quay.io registry

2. Kubernetes Environment Testing:
   - Platform: AWS EKS cluster with ARM64 EC2 nodes
   - Deployment: Successfully deployed the webhook on ARM64 nodes
   - Functionality: Created KCLRun objects and verified that mutations were correctly applied

This comprehensive testing confirms that the ARM64 build works correctly in a production-like environment, maintaining all expected functionality of the webhook.

### CODE REVIEW

**Comment by suin** [comment]
I've submitted this PR to demonstrate one possible approach to the ARM64 support discussed in #64. If you have a different direction in mind or see any concerns with this approach, please feel free to let me know. I'm happy to adjust or reconsider the implementation based on your feedback.

**Review by zong-zhe — APPROVED** [review]
LGTM ! 😄  Thank you for your contributions and welcome to be a KCL contributor ! cc @He1pa

**Comment by He1pa** [comment]
nice work! lgtm

**Comment by suin** [comment]
Thank you for the review and merge! Happy to contribute to the KCL project. 🙂

**Pull request merged**
